import argparse
import importlib.metadata
import json
import os
from pathlib import Path
import signal
import subprocess
import sys

from .aggregate import aggregate, export_results, status
from .manifests import REPO, build_manifest, load_config, resolve, row_path, validate_manifest
from .schemas import Invalid, canonical, digest
from .storage import Journal, atomic_json, immutable_json, read_json, row_lock

PHASES = ("inventory", "collect", "replay", "discover", "confirm", "reuse")


def source_metadata():
    files = list((Path(__file__).parent).glob("*.py")) + [REPO / "seek_eval.py", REPO / "seek_eval.sh", REPO / "seek_submit.sh", REPO / "seek_qwen.sh"]
    files += list((Path(__file__).parents[1] / "defenses").glob("*.py")) + [Path(__file__).parents[1] / "test.py"]
    sources = {str(p.relative_to(REPO)): digest(p.read_text()) for p in files if p.exists()}
    try:
        git = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=REPO, text=True, stderr=subprocess.DEVNULL).strip()
    except (OSError, subprocess.CalledProcessError):
        git = None
    return {"git_commit": git, "source_hash": digest(sources), "files": sources}


def safe_pip_freeze():
    try:
        lines = subprocess.check_output([sys.executable, "-m", "pip", "freeze"], text=True, stderr=subprocess.DEVNULL).splitlines()
        return [line if "://" not in line and not line.startswith("-e ") else "source_reference_hash=" + digest(line) for line in lines]
    except (OSError, subprocess.CalledProcessError) as exc:
        return ["unavailable:" + type(exc).__name__]


def load_snapshots(root):
    from .snapshot_io import validate_snapshot
    values = [read_json(p) for p in sorted((Path(root) / "snapshots").glob("*.json"))]
    for value in values:
        validate_snapshot(value)
    return values


def run(config, phase, row_index, resume=False, override=None):
    from .provenance import checkpoint_entry, preflight, verify_weights
    row = config["rows"][row_index] if 0 <= row_index < len(config["rows"]) else None
    root = row_path(config, row_index, override)
    check = preflight(config, row_index, phase)
    if check["status"] != "ready":
        raise Invalid(canonical(check))
    if not config["simulated"]:
        if not os.environ.get("SLURM_JOB_ID"):
            raise Invalid("real runtime requires an allocated Slurm worker; no GPU work on notebook/login")
        if phase == "discover" and "local" not in config["agents"] and not os.environ.get("OPENAI_API_KEY"):
            raise Invalid("trusted defender API credential missing from environment")
    immutable_json(root.parents[1] / "planned_rows.json", {"simulated": config["simulated"],
                   "rows": [str(row_path(config, i, override).relative_to(root.parents[1])) for i in range(len(config["rows"]))]})
    with row_lock(root):
        source = source_metadata()
        identity = {"config": config, "row": row_index, "source_hash": source["source_hash"]}
        exists = (root / "resolved_config.json").exists()
        if exists and not resume:
            raise Invalid("row exists; use --resume or a new run_id")
        immutable_json(root / "resolved_config.json", dict(config, selected_row=row_index))
        immutable_json(root / "run_manifest.json", identity)
        immutable_json(root / "source.json", source)
        journal = Journal(root)
        destination = root / (phase + ".json")
        if destination.exists() and any(r["kind"] == "phase_complete" and r["data"]["phase"] == phase and
                                        r["data"]["result_hash"] == digest(read_json(destination)) for r in journal.records):
            return read_json(destination)
        start = journal.emit("phase_start", {"phase": phase, "simulated": config["simulated"]})
        atomic_json(root / "active.json", {"phase": phase, "status": "incomplete"})
        try:
            if phase == "inventory":
                from .collection import inventory_real
                if config["simulated"]:
                    raise Invalid("fake inventory is generated by collect")
                result = inventory_real(config)
            else:
                if config["simulated"]:
                    from .victim import FakeVictim
                    victim = FakeVictim(config["fake_scenario"])
                else:
                    from .victim import LegacyVictim
                    entry = checkpoint_entry(config, row)
                    verify_weights(entry)
                    victim = LegacyVictim(entry, config["victim"])
                    (root / "private_eval").mkdir(mode=0o700, exist_ok=True)
                    immutable_json(root / "private_eval" / "checkpoint_provenance.json", entry)
                    immutable_json(root / "runtime_environments" / (os.environ["SLURM_JOB_ID"] + ".json"), {
                        "packages": sorted(f"{d.metadata['Name']}=={d.version}" for d in importlib.metadata.distributions()),
                        "pip_freeze": safe_pip_freeze(),
                        "slurm_job_id": os.environ.get("SLURM_JOB_ID"),
                        "slurm_array_task_id": os.environ.get("SLURM_ARRAY_TASK_ID"),
                        "gpu": victim.torch.cuda.get_device_name(0), "visible_device": 0,
                        "dtype": victim.dtype, "defender_model_requested": config["agents"]["model"]})
                result = execute_phase(config, row, root, phase, victim, journal)
            atomic_json(destination, result)
            journal.emit("phase_complete", {"phase": phase, "start_id": start, "result_hash": digest(result)})
            # Older interrupted starts of this same deterministic phase are now recovered.
            for old in list(journal.records):
                if old["kind"] == "phase_start" and old["data"]["phase"] == phase and old["id"] != start and not any(
                        r["kind"] == "phase_complete" and r["data"]["start_id"] == old["id"] for r in journal.records):
                    journal.emit("phase_complete", {"phase": phase, "start_id": old["id"], "result_hash": digest(result), "recovered": True})
            atomic_json(root / "active.json", {"phase": phase, "status": "complete"})
            write_summary(root, config, source, journal)
            return result
        except BaseException as exc:
            journal.emit("phase_failure", {"phase": phase, "error_type": type(exc).__name__})
            atomic_json(root / "active.json", {"phase": phase, "status": "incomplete"})
            write_summary(root, config, source, journal)
            raise


def execute_phase(config, row, root, phase, victim, journal):
    if phase == "collect":
        from .collection import collect_fake, collect_real
        manifest, snapshots = (collect_fake if config["simulated"] else collect_real)(config, row, victim, journal, root)
        return {"status": "complete", "captured": len(snapshots), "eligible_tasks": len(manifest["tasks"]), "simulated": config["simulated"]}
    snapshots = load_snapshots(root)
    if not snapshots:
        raise Invalid("no complete captured snapshots; run collect first")
    if any(s["public"]["simulated"] != config["simulated"] for s in snapshots):
        raise Invalid("fake/real evidence segregation violation")
    if phase == "replay":
        from .replay import no_edit_replay
        return {"status": "complete", "records": [no_edit_replay(victim, s, journal, config["budgets"]["replay_victim"]) for s in snapshots],
                "simulated": config["simulated"]}
    if phase == "discover":
        from .controller import discover
        from .roles import Discussion, FakeRoles, OpenAIRoles
        if not (root / "replay.json").exists():
            raise Invalid("run replay audit before discovery")
        replays = {r["case_id"]: r for r in read_json(root / "replay.json")["records"]}
        eligible = [s for s in snapshots if s["public"]["split"] == "discovery"]
        if not eligible:
            eligible = [s for s in snapshots if s["public"]["split"] == "development"]
        if not eligible:
            raise Invalid("no discovery/development contexts; never substitute holdouts")
        selected = sorted(eligible, key=lambda s: s["public"]["case_id"])[0]
        from .local_roles import LocalRoles
        backend = FakeRoles() if config["simulated"] else (LocalRoles(config["agents"]) if "local" in config["agents"] else OpenAIRoles(config["agents"]))
        discussion = Discussion(backend, config, journal)
        try:
            result = discover(selected, replays.get(selected["public"]["case_id"], {}), victim, discussion, journal, config, row["method"])
        except Invalid as exc:
            result = {"status": "backend_failure", "candidate": None, "reason": str(exc)}
        finally:
            if hasattr(backend, "close"):
                backend.close()
        result.update(discovery_case_id=selected["public"]["case_id"], simulated=config["simulated"])
        from .confirmation import freeze
        frozen = freeze(result, selected, snapshots, config["confirmation"], root / "frozen_candidate.json")
        result["frozen_hash"] = frozen["hash"] if frozen else None
        return result
    if phase == "confirm":
        from .confirmation import claim_holdouts, confirm
        from .signatures import make_signature
        if not (root / "frozen_candidate.json").exists():
            return {"status": "inconclusive", "reason": "no_frozen_candidate", "evaluator_functional_validated": False, "simulated": config["simulated"]}
        frozen = read_json(root / "frozen_candidate.json")
        family_path = root.parents[1] / "family_registration.json"
        claim_holdouts(root.parents[2], frozen, read_json(family_path) if family_path.exists() else None)
        manifest = read_json(root / "task_manifest.json")
        result = confirm(frozen, snapshots, victim, journal, config, row["method"], manifest["overlap_status"])
        signature = make_signature(frozen, result, read_json(root / "discover.json").get("method_victim_queries", 0))
        if signature:
            immutable_json(root / "signature.json", signature)
        return result
    if phase == "reuse":
        from .signatures import reuse
        if not (root / "signature.json").exists():
            return {"status": "inconclusive", "reason": "no_validated_signature", "simulated": config["simulated"]}
        return reuse(read_json(root / "signature.json"), snapshots, victim, journal, config["budgets"]["reuse_victim"])
    raise Invalid("unknown phase")


def write_summary(root, config, source, journal):
    from .metrics import call_metrics, denominator_summary
    def optional(phase):
        path = root / (phase + ".json")
        return read_json(path) if path.exists() else None
    confirmation = optional("confirm")
    summary = {"schema_version": 1, "simulated": config["simulated"], "source_hash": source["source_hash"],
               "counts": denominator_summary(load_snapshots(root), (optional("replay") or {}).get("records", []), optional("discover"), confirmation),
               "costs": call_metrics(journal.records), "confirmation_status": confirmation.get("status") if confirmation else None,
               "checkpoint_training_status": read_json(root / "private_eval" / "checkpoint_provenance.json")["training_status"] if (root / "private_eval" / "checkpoint_provenance.json").exists() else "simulated" if config["simulated"] else "unknown",
               "phase_statuses": {p: optional(p).get("status", "complete") if optional(p) else "missing" for p in PHASES}}
    selected_row = read_json(root / "resolved_config.json")["selected_row"]
    summary["condition"] = {k: config["rows"][selected_row][k] for k in ("checkpoint_alias", "channel", "category", "method", "track")}
    summary["counts"]["eligible_tasks"] = (optional("collect") or {}).get("eligible_tasks")
    summary["counts"]["unscorable_arms"] = sum(r["kind"] == "confirmation_arm" and r["data"]["score"]["y"] is None for r in journal.records)
    summary["counts"]["preservation_failures"] = sum(r["kind"] == "preservation_failure" for r in journal.records)
    atomic_json(root / "summary.json", summary)
    (root / "audit.md").write_text("Seek evidence audit\n\n" + ("SIMULATED CPU fixtures; no trained-model evidence.\n" if config["simulated"] else
                                    "Real runtime requested; inspect replay and phase failures before interpreting results.\n") +
                                    "Next-proposal scope only. No delayed branched rollout support. Exact recovery requires private ground truth.\n")


def parser():
    p = argparse.ArgumentParser(description="Isolated Seek Stage II; default metadata operations are CPU-only")
    commands = p.add_subparsers(dest="command", required=True)
    for command in ("preflight", "run", "schedule"):
        s = commands.add_parser(command)
        s.add_argument("--config", required=True)
        s.add_argument("--row", type=int, default=None)
        s.add_argument("--phase", choices=PHASES, required=command != "preflight")
        s.add_argument("--run-root")
        if command == "preflight":
            s.add_argument("--metadata-only", action="store_true", required=True)
        if command == "run":
            s.add_argument("--resume", action="store_true")
    for command in ("aggregate", "status", "export-results"):
        s = commands.add_parser(command)
        s.add_argument("--run-root", required=True)
        if command == "export-results":
            s.add_argument("--output", required=True)
    s = commands.add_parser("register-family")
    s.add_argument("--run-root", required=True)
    s = commands.add_parser("score-private")
    s.add_argument("--run-root", required=True)
    s.add_argument("--labels", required=True)
    s = commands.add_parser("build-manifest")
    s.add_argument("--inventory", required=True)
    s.add_argument("--sizes", required=True, help="JSON object: independent groups per split")
    s.add_argument("--training-fingerprints")
    s.add_argument("--output", required=True)
    s = commands.add_parser("audit-assets")
    s.add_argument("--product-file", required=True)
    s.add_argument("--num-products", type=int)
    s.add_argument("--output", required=True)
    s = commands.add_parser("audit-checkpoint")
    s.add_argument("--checkpoint", required=True)
    s.add_argument("--output", required=True)
    s = commands.add_parser("import-legacy")
    s.add_argument("--input", required=True)
    s.add_argument("--output", required=True)
    return p


def main(argv=None):
    args = parser().parse_args(argv)
    def terminate(signum, frame):
        raise KeyboardInterrupt("Slurm termination; partial evidence retained")
    signal.signal(signal.SIGTERM, terminate)
    try:
        if args.command in ("run", "preflight", "schedule"):
            config = load_config(args.config)
            rows = [args.row] if args.row is not None else list(range(len(config["rows"])))
            for row in rows:
                row_path(config, row, args.run_root)
            if args.command == "schedule":
                result = [{"row": row, "checkpoint_alias": config["rows"][row]["checkpoint_alias"],
                           "config": str(Path(args.config).resolve()), "phase": args.phase,
                           "output": str(row_path(config, row, args.run_root)), "simulated": config["simulated"]} for row in rows]
            elif args.command == "preflight":
                from .provenance import preflight
                result = [dict(row=row, **preflight(config, row, args.phase)) for row in rows]
                print(json.dumps(result, indent=2))
                return 2 if any(r["status"] == "blocked" for r in result) else 0
            else:
                result = [run(config, args.phase, row, args.resume, args.run_root) for row in rows]
        elif args.command == "aggregate":
            result = aggregate(args.run_root)
        elif args.command == "status":
            result = status(args.run_root)
        elif args.command == "export-results":
            result = export_results(args.run_root, args.output)
        elif args.command == "register-family":
            from .confirmation import register_family
            result = register_family(args.run_root)
        elif args.command == "score-private":
            from .evaluator import score_private
            result = score_private(args.run_root, args.labels)
        elif args.command == "build-manifest":
            result = build_manifest(read_json(args.inventory), json.loads(args.sizes),
                                    read_json(args.training_fingerprints) if args.training_fingerprints else None)
            immutable_json(args.output, result)
        elif args.command == "audit-assets":
            from .provenance import audit_assets, environment_source_hash
            result = audit_assets(args.product_file, args.num_products)
            immutable_json(args.output, result)
            result = {"output": args.output, "catalogue_hash": digest(result["files"]), "environment_hash": environment_source_hash()}
        elif args.command == "audit-checkpoint":
            from .provenance import audit_checkpoint
            result = audit_checkpoint(args.checkpoint)
            immutable_json(args.output, result)
        else:
            from .snapshot_io import import_legacy
            result = import_legacy(args.input)
            immutable_json(args.output, result)
        print(json.dumps(result, indent=2))
        return 0
    except KeyboardInterrupt:
        print("Seek interrupted; resume retains attempted-call provenance", file=sys.stderr)
        return 130
    except (Invalid, OSError, ValueError) as exc:
        print("Seek: " + str(exc), file=sys.stderr)
        return 2
