"""Schemas and metrics for the WebShop choice-integrity benchmark.

The package intentionally depends only on the Python standard library so that
manifests and completed episode files can be checked on login nodes as well as
inside the evaluation environment.
"""

from .metrics import (
    aggregate_by_cell,
    aggregate_metrics,
    clustered_bootstrap_ci,
    preference_flip_metrics,
)
from .baselines import (
    CallableStateAwareVerifier,
    DeterministicDominanceVerifier,
    DeterministicVerifierStub,
    GoalOnlyBaseline,
    OpenAIStateAwareVerifier,
    StateAwareVerifier,
    StateAwareVerifierDefense,
    UndefendedBaseline,
    VerifierRequest,
    VerifierStatus,
    VerifierVerdict,
)
from .contract import (
    PRICE_PREFERENCE_SUFFIX,
    RATING_PREFERENCE_SUFFIX,
    ChoiceContract,
    FixedSuffixPreferenceParser,
    PreferenceProvenance,
)
from .defense import (
    CHOICE_INTEGRITY_ABLATIONS,
    AvailableActions,
    ChoiceDecision,
    ChoiceIntegrityDefense,
    ChoiceIntegrityGuard,
    DecisionStatus,
    DeterministicChoicePlanner,
    PlanResult,
    RuntimeDecision,
    is_commitment_action,
    parse_action,
)
from .ledger import (
    CandidateLedger,
    EvidenceObservation,
    LedgerEntry,
    LedgerError,
    LedgerIncompleteError,
)
from .schema import (
    Benchmark,
    BenchmarkManifest,
    Candidate,
    ChoiceTask,
    Condition,
    EpisodeResult,
    FrozenDict,
    Preference,
    PreferenceKind,
    SchemaError,
    candidate_identity,
    canonical_json,
    dominates,
    hard_feasible_winners,
    price_regret,
    rating_regret,
)

__all__ = [
    "CHOICE_INTEGRITY_ABLATIONS",
    "PRICE_PREFERENCE_SUFFIX",
    "RATING_PREFERENCE_SUFFIX",
    "AvailableActions",
    "Benchmark",
    "BenchmarkManifest",
    "CallableStateAwareVerifier",
    "Candidate",
    "CandidateLedger",
    "ChoiceContract",
    "ChoiceDecision",
    "ChoiceIntegrityDefense",
    "ChoiceIntegrityGuard",
    "ChoiceTask",
    "Condition",
    "DecisionStatus",
    "DeterministicChoicePlanner",
    "DeterministicDominanceVerifier",
    "DeterministicVerifierStub",
    "EvidenceObservation",
    "EpisodeResult",
    "FixedSuffixPreferenceParser",
    "FrozenDict",
    "GoalOnlyBaseline",
    "LedgerEntry",
    "LedgerError",
    "LedgerIncompleteError",
    "OpenAIStateAwareVerifier",
    "PlanResult",
    "Preference",
    "PreferenceKind",
    "PreferenceProvenance",
    "RuntimeDecision",
    "SchemaError",
    "StateAwareVerifier",
    "StateAwareVerifierDefense",
    "UndefendedBaseline",
    "VerifierRequest",
    "VerifierStatus",
    "VerifierVerdict",
    "aggregate_by_cell",
    "aggregate_metrics",
    "candidate_identity",
    "canonical_json",
    "clustered_bootstrap_ci",
    "dominates",
    "hard_feasible_winners",
    "is_commitment_action",
    "parse_action",
    "preference_flip_metrics",
    "price_regret",
    "rating_regret",
]
